// <auto-generated />
namespace App.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-beta1-60406")]
    public sealed partial class addedcolumnstosupplier : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedcolumnstosupplier));
        
        string IMigrationMetadata.Id
        {
            get { return "201711280732586_addedcolumns tosupplier"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
