//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App
{
    using System;
    using System.Collections.Generic;
    
    public partial class pos_order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pos_order()
        {
            this.pos_order_line = new HashSet<pos_order_line>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public Nullable<int> sale_journal { get; set; }
        public string pos_reference { get; set; }
        public Nullable<int> write_uid { get; set; }
        public Nullable<int> account_move { get; set; }
        public Nullable<System.DateTime> date_order { get; set; }
        public Nullable<int> partner_id { get; set; }
        public Nullable<int> nb_print { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> location_id { get; set; }
        public int company_id { get; set; }
        public string note { get; set; }
        public string state { get; set; }
        public int pricelist_id { get; set; }
        public Nullable<int> create_uid { get; set; }
        public Nullable<System.DateTime> write_date { get; set; }
        public Nullable<int> fiscal_position_id { get; set; }
        public string name { get; set; }
        public Nullable<int> invoice_id { get; set; }
        public int session_id { get; set; }
        public Nullable<int> picking_id { get; set; }
        public Nullable<int> sequence_number { get; set; }
        public Nullable<int> customer_count { get; set; }
        public Nullable<int> table_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pos_order_line> pos_order_line { get; set; }
    }
}
