//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App
{
    using System;
    using System.Collections.Generic;
    
    public partial class pos_order_line
    {
        public int id { get; set; }
        public Nullable<int> create_uid { get; set; }
        public string notice { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public string name { get; set; }
        public Nullable<int> order_id { get; set; }
        public Nullable<decimal> price_unit { get; set; }
        public int company_id { get; set; }
        public Nullable<decimal> qty { get; set; }
        public Nullable<decimal> discount { get; set; }
        public Nullable<int> write_uid { get; set; }
        public Nullable<System.DateTime> write_date { get; set; }
        public int product_id { get; set; }
    
        public virtual pos_order pos_order { get; set; }
    }
}
