//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App
{
    using System;
    using System.Collections.Generic;
    
    public partial class res_users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public res_users()
        {
            this.pos_order = new HashSet<pos_order>();
            this.pos_order1 = new HashSet<pos_order>();
            this.pos_order2 = new HashSet<pos_order>();
            this.pos_order_line = new HashSet<pos_order_line>();
            this.pos_order_line1 = new HashSet<pos_order_line>();
            this.res_users1 = new HashSet<res_users>();
            this.res_users11 = new HashSet<res_users>();
        }
    
        public int id { get; set; }
        public Nullable<bool> active { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public int company_id { get; set; }
        public int partner_id { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public Nullable<bool> share { get; set; }
        public Nullable<int> write_uid { get; set; }
        public Nullable<int> create_uid { get; set; }
        public Nullable<int> action_id { get; set; }
        public Nullable<System.DateTime> write_date { get; set; }
        public string signature { get; set; }
        public string password_crypt { get; set; }
        public Nullable<int> alias_id { get; set; }
        public string pos_security_pin { get; set; }
        public Nullable<bool> isverified { get; set; }
        public string login_type { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pos_order> pos_order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pos_order> pos_order1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pos_order> pos_order2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pos_order_line> pos_order_line { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pos_order_line> pos_order_line1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<res_users> res_users1 { get; set; }
        public virtual res_users res_users2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<res_users> res_users11 { get; set; }
        public virtual res_users res_users3 { get; set; }
    }
}
